config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :foods do
    resources :orders, except: [:destroy] do
      resources :reviews, only: [:create]
    end
  end
  resources :orders, only: [:destroy] #do
     # resources :reviews, only: [:create]
  #end
  get "dashboard", to: "dashboards#dashboard", as: :dashboard
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :order
  has_many :review, through: :order
  validates :name, presence: true
  validates :prepared_at, presence: true
  validates :location, presence: true
  validates :price, presence: true

  include AlgoliaSearch

  algoliasearch do
    attributes :name, :location, :price
  end
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  mount_uploader :photo, PhotoUploader

  def hours_passed
    if self.prepared_at.nil?
      0
    else
      ((Time.now - self.prepared_at) / 3600)
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :food
  belongs_to :user
  has_many :review
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :order
  validates :rating, presence: true, inclusion: { in: [1, 2, 3, 4, 5] }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_many :foods
  has_many :reviews, through: :foods
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :photo, PhotoUploader

  def avg_rating
    # reviews.pluck(:rating).sum / reviews.length
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
      # For additional fields in app/views/devise/registrations/new.html.erb
      devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :address, :photo])

      # For additional in app/views/devise/registrations/edit.html.erb
      devise_parameter_sanitizer.permit(:account_update, keys: [:photo, :address])
    end
  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def dashboard
    @foods =  policy_scope(Food).where(user: current_user).order(created_at: :asc)
    @orders = policy_scope(Order).where(user: current_user).order(created_at: :asc)
    skip_authorization
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  def index
    #1serach and found
    #2search and not found
    #3no search
    #look for items then if found present


    # foods = all foods
    # if searching
    #   results = search
    #   if results are not empty
    #     foods = results
    #   else
    #     message = 'error message'
    #   end
    # end





    @foods = policy_scope(Food).order(created_at: :asc)

    if params[:food].present?
      puts params
      puts "Searching for #{params[:food][:name]}"
      @foods = Food.search(params[:food][:name])
      # @name_foods = Food.search(params["food"]["name"])
      # @fresh_foods = Food.search(params["food"]["freshness"])
      # @locat_foods = Food.search(params["food"]["location"])
      # @foods = @name_foods & @locat_foods
    else
      @message = "Sorry we couldn't find what youre searching, here are some suggestions:"
      @foods = policy_scope(Food).order(created_at: :asc)
    end
  end
 # if params[:query].present?
 #      @movies = Movie.where(title: params[:query])
 #    else
 #      @movies = Movie.all
 #    end


 def show
  @food = Food.find(params[:id])
  @markers = [
    {
      lat: @food.latitude,
      lng: @food.longitude
    }]
  end

  def edit
  end

  def new
    @food = Food.new
    authorize @food
  end

  def create
    @food = Food.new(food_params)
    date = params[:food][:prepared_at].split[0].split("-").map{|e| e.to_i}
    time = params[:food][:prepared_at].split[1].split(":").map{|e| e.to_i}
    @food.prepared_at = DateTime.new(date[0], date[1], date[2], time[0], time[1], 0)
    @food.user = current_user
    authorize @food

    if @food.save
      redirect_to @food
    else
      render :new
    end
  end

  def update
    if @food.update(food_params)
      redirect_to @food, notice: 'food has been successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @food.destroy
    redirect_to foods_path, notice: 'food has been successfully deleted'
  end

  private

  def set_food
    @food = Food.find(params[:id])
    authorize @food
  end

  def food_params
   params.require(:food).permit(:name, :prepared_at, :location, :description, :price, :photo)
 end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    @order = Order.new
    @food = Food.find(params[:food_id])
    @order.food = @food
    authorize @order
    @order.user = current_user
    if @order.save
      redirect_to food_order_path(id: @order.id)
    else
      redirect_to foods_path, notice: 'there was a problem with your order'
    end
  end

  def show
    @order = Order.find(params[:id])
    @food = Food.find(params[:food_id])
    @review = Review.new(order_id: @order.id)
    authorize @food
    authorize @order
  end

  def delete
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @foods = Food.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @order = Order.find(params[:order_id])
    @review.order = @order
    authorize @review
    @review.save
  end

  private

  def review_params
    params.require(:review).permit(:rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/dashboard.html.erb
<div class="dashboard-head row justify-content-between m-5" >
  <h1>Dashboard</h1>
  <%= link_to "Couldn't finish something?", new_food_path %>
</div>

<div class="container">
  <h3>My sharing rating: <%= current_user.avg_rating %></h3>
<div class="tabset">
  <input type="radio" name="tabset" id="tab1" aria-controls="What you've shared" checked>
  <label for="tab1"><h2>What you've shared</h2></label>
  <input type="radio" name="tabset" id="tab2" aria-controls="What you've ordered">
  <label for="tab2"><h2>What you've ordered</h2></label>
  <div class="tab-panels">
    <section id="What you've shared" class="tab-panel">
    <div class="container index-container">
      <div class="row">
        <% @foods.each do |food| %>
        <div class="col-md-4 col-sm-12">
          <div class="dashboard-card">
            <div class="card">
              <% if food.photo.url.nil? %>
              <img src="https://source.unsplash.com/1600x900/?<%= food.name %>" class="card-img-top" alt="food-image">
              <% else %>
              <%= cl_image_tag food.photo %>
              <% end %>
              <div class="dashboard-card-content">
                <h5 class="card-title"><%= food.name %></h5>
                <p class="card-text"><%= render partial: 'shared/food_emoji', locals: {food: food}%></p>
                <p class="card-text index-card-price"><strong><i class="fas fa-dollar-sign"></i>  </strong><%= food.price %></p>
                <p> <%= link_to 'Show', food %></p>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    </section>
    <section id="What you've ordered" class="tab-panel">
    <div class="container index-container">
      <div class="row">
        <% @orders.each do |order| %>
        <div class="col-md-4 col-sm-12">
          <div class="dashboard-card">
            <div class="card">
              <% if order.food.photo.url.nil? %>
              <img src="https://source.unsplash.com/1600x900/?<%= order.food.name %>" class="card-img-top" alt="food-image">
              <% else %>
              <%= cl_image_tag order.food.photo %>
              <% end %>
              <div class="dashboard-card-content">
                <h5 class="card-title"><%= order.food.name %></h5>
                <p class="card-text"><%= render partial: 'shared/food_emoji', locals: {food: order.food}%></p>
                <p class="card-text index-card-price"><strong><i class="fas fa-dollar-sign"></i>  </strong><%= order.food.price %></p>
                <%= cl_image_tag order.food.photo, class: "card-text" %>
                <p> <%= link_to 'Show', order %></p>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </section>
  </div>
</div>
</div>

app/views/foods/_form.html.erb
<%= simple_form_for(@food) do |f| %>
<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
<div class="row justify-content-md-center">
  <div class="form-inputs card">
    <li class="btn btn-light">
      <%= f.input :name %>
    </li>
    <li class="btn btn-light">
      <%= f.input :prepared_at, placeholder: 'Time since food was partially eaten', as: :string, required: false, input_html: {class: "datepicker"} %>
    </li>
    <li class="btn btn-light">
      <%= f.input :location %>
    </li>
    <li class="btn btn-light">
      <%= f.input :price %>
    </li>
    <li class="btn btn-light">
      <%= f.input :photo %>
    </li>
    <li type="button" class="btn btn-success">
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.button :submit %>
      </button>
    </li>
  </div>
</div>
<% end %>

app/views/foods/edit.html.erb
<div>
<h1>Edit your food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Back', foods_path %>
</div>

app/views/foods/index.html.erb
<div class="container index-container">
  <h2><%= @message %></h2>
  <div class="row">
    <% @foods.each do |food| %>
      <% if food.order.empty? %>
        <div class="col-md-4 col-sm-12">
          <div class="card mb-3 index-card">
            <% if food.photo.url.nil? %>
              <img src="https://source.unsplash.com/1600x900/?<%= food.name %>" class="card-img-top" alt="food-image">
            <% else %>
              <%= cl_image_tag food.photo %>
            <% end %>
            <div class="card-body">
              <% if policy(food).edit? %>
                <%= link_to edit_food_path(food), class: "show-icons" do %>
                  <i class="far fa-edit"></i>
                <% end %>
                <%= link_to food_path(food), method: :delete, class: "show-icons" do %>
                  <i class="fas fa-trash-alt"></i>
                <% end %>
              <% end %>
              <h5 class="card-title"><%= food.name %></h5>
              <p class="card-text">Freshness:
          <%= render partial: 'shared/food_emoji', locals: {food: food}%></p>
              <p class="card-text index-card-price"><strong><i class="fas fa-dollar-sign"></i>  </strong><%= food.price %></p>
              <%= link_to "Yum!", food_path(food), class: "btn btn-success"%>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/foods/new.html.erb
<center><div class="form-header">
<h1 class="mt-10">What do you have left over?</h1>
<%= render 'form', food: @food %>
<br>
<button type="button" class="btn btn-light">
<%= link_to 'Back', foods_path %>
</button>
</div>
</center>

app/views/foods/show.html.erb
<div class="show-card">
  <% if @food.photo.url.nil? %>
  <img src="https://source.unsplash.com/1600x900/?<%= @food.name %>" alt="food image">
  <% else %>
  <%= cl_image_tag @food.photo %>
  <% end %>
  <div class="show-card-content">
    <div class="show-card-head">
      <h2><%= @food.name %></h2>
      <% if policy(@food).edit? %>
        <%= link_to edit_food_path, class: "show-icons" do %>
          <i class="far fa-edit"></i>
        <% end %>
        <%= link_to food_path(@food), method: :delete, class: "show-icons" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      <% end %>
    </div>
    <div class="show-card-body">
      <p><strong>Freshness: </strong><%= render partial: 'shared/food_emoji', locals: {food: @food}%></p>
      <p><strong>$</strong><%= @food.price %></p>
      <p><%= @food.location %></p>
    </div>

    <%= link_to "Bite it!", food_orders_path(@food), method: 'post', class: "btn btn-success"%>
  </div>

</div>

<div
id="map"
style="width: 100%;
height: 600px;"
data-markers="<%= @markers.to_json %>"
data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Freshtovers</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <link href="https://emoji-css.afeld.me/emoji.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    </head>
    <body>
      <%= render 'shared/navbar'  %>
      <%= render 'shared/flashes'  %>
      <div class="content">
        <%= yield %>
      </div>
      <%= javascript_include_tag 'application' %>
      <%= javascript_pack_tag 'application' %>
  <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
  <script>
    AOS.init();
  </script>
    </body>
    <footer>
      <%= render 'shared/footer'  %>
    </footer>
  </html>

app/views/orders/show.html.erb
<body>
  <h1>Order Confirmed</h1>

  <div class="show-food card mx-auto" style="max-width: 1000px;">
    <div class="row">
      <div class="col-md-4">
        <img src="https://source.unsplash.com/1600x900/?<%= @food.name %>" class="card-img-top img-fluid" alt="food image">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h2 class="card-title"><%= @food.name %></h2>
          <p class="card-text">Freshness:
              <%= render partial: 'shared/food_emoji', locals: {food: @food}%></p>
            <p class="card-text">Rating:
              <%= simple_form_for([@order.food, @order, @review]) do |f| %>
              <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience" %>
              <%= f.submit class: "d-none" %>

              <% end %>
            </p>
            <p class="card-text index-card-price"><strong><i class="fas fa-dollar-sign"></i>  </strong><%= @food.price %></p>
            <p class="card-text"><%= @food.location %></p>
            <p class="card-text"><small class="text-muted"><%= @food.updated_at %></small></p>
        </div>

      </div>
    </div>
  </div>
</body>

app/views/pages/home.html.erb
<div class="banner" style="background-image: url(<%= image_path "people-shared.png" %>)">
  <div class="search-form-wrapper col-4 col-md-4 offset-md-1 col-xl-4 offset-xl-1">
    <%= render 'shared/search-form' %>
  </div>
</div>


<div class="container index-container">
<div class="row">
  <% @foods.each do |food| %>
  <% if food.order.empty? %>
  <div class="col-md-4 col-sm-12">
  <div data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">
  <div class="card mb-3 home-card">
    <% if food.photo.url.nil? %>
    <img src="https://source.unsplash.com/1600x900/?<%= food.name %>" class='card-img-top' alt="food-image">
    <% else %>
    <%= cl_image_tag food.photo %>
    <% end %>
      <div class="card-body">
      <div>
        <h2 class="card-title"><%= food.name  %></h2>
        <p class="card-text">Freshness:
        <%= render partial: 'shared/food_emoji', locals: {food: food}%></p>
        <p class="card-text index-card-price"><strong><i class="fas fa-dollar-sign"></i>  </strong><%= food.price %></p>
      </div>
    </div>
  </div>
  </div>
</div>
  <% end %>
  <% end %>
</div>
  <%= javascript_pack_tag 'typed' %>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= simple_form_for @review do |f| %>
        <%= f.input :content %>
        <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience" %>
        <%= f.submit "Send your review" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_food_emoji.html.erb
<% if food.hours_passed == 0 %>
    <i class="em em-zipper_mouth_face" aria-role="presentation" aria-label="ZIPPER-MOUTH FACE"></i>
<% elsif food.hours_passed <= 48 %>
    <i class="em em-drooling_face" aria-role="presentation" aria-label="DROOLING FACE"></i>
<% elsif food.hours_passed <= 96 %>
    <i class="em em-expressionless" aria-role="presentation" aria-label="EXPRESSIONLESS FACE"></i>
<% else %>
    <i class="em em-cold_sweat" aria-role="presentation" aria-label="FACE WITH OPEN MOUTH AND COLD SWEAT"></i>
<% end  %>

app/views/shared/_footer.html.erb
<footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <h6>About</h6>
            <p class="text-justify">leftovers.com - the intiaitive to eliminate food waste! </p>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Categories</h6>
            <ul class="footer-links">
              <li><a href="Starters">Starters</a></li>
              <li><a href="Drinks">Drinks</a></li>
              <li><a href="Main Course">Main Course</a></li>
              <li><a href="Desserts">Desserts</a></li>
              <li><a href="Miscellaneous">Miscellaneous</a></li>
            </ul>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Quick Links</h6>
            <ul class="footer-links">
              <li><a href="#">About Us</a></li>
              <li><a href="#">Contact Us</a></li>
            </ul>
          </div>
        </div>
        <hr>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Copyright &copy; 2019 All Rights Reserved by
         <a href="#">Leftovers</a>.
            </p>
          </div>

          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
              <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
  <%= cl_image_tag "05155580-9227-4627-92da-9a818714e1a5_200x200_ekcbxq", crop: :fill %>
  <% end %>
  <div class="topnav-centered">
    <a class="active"><h3>Freshtovers</h3>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <button class="btn btn-light">
          <%= link_to "Home", root_path, class: "nav-link" %>
          </button>
        </li>
        <li>
          <button class="btn btn-light">
          <%= link_to "Available Food", foods_path, class: "nav-link" %>
          </button>
        </li>
        <li>
          <button class="btn btn-light">
          <%= link_to "Post", new_food_path, class: "nav-link" %>
          </button>
        </li>
        <li class="nav-item dropdown btn btn-light">
          <% if current_user.photo.file.nil? %>
            <%= cl_image_tag "blank-avatar_rupjxt", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= current_user.email %>
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
        <% else %>
        <li class="nav-item btn btn-light">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item btn btn-light">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item btn btn-light">
          <%= link_to "Sign-up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_search-form.html.erb
<%= simple_form_for(Food.new, method: 'get') do |f| %>
<%= f.input :name, input_html: {id:"typed"},  label: false  %>

  <div class="text-center">
    <%= f.submit :SEARCH, class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

  <!-- MAKE A SLIDER FOR FRESHNESS -->
  <!-- Change the "name" search to "food" search -->